# Generated by Django 4.1.7 on 2023-04-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_repair_repairimage_repair_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liders',
            old_name='Model',
            new_name='model',
        ),
    ]
