# Generated by Django 4.1.7 on 2023-06-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_repair_lidersimage_liders'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='pulbirligi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='pulbirligi_ru',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='pulbirligi_uz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
