# Generated by Django 4.1.7 on 2023-04-17 10:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_model_liders_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
