# Generated by Django 4.1.7 on 2023-04-17 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_news_description_ru_news_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='address_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='address_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
