# Generated by Django 4.1.7 on 2023-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_liders_brend_ru_liders_brend_uz_liders_country_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoborodvnya',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryoborodvnya',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
