# Generated by Django 4.1.7 on 2023-04-19 05:12

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_categoryoborodvnya_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='brand_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='country_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='country_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pulbirligi',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='pulbirligi_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pulbirligi_uz',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
