# Generated by Django 4.1.7 on 2023-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_equipment_brand_ru_equipment_brand_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryreagents',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryreagents',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='manufacturer_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='manufacturer_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='model_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='model_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='supplier_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='supplier_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reagents',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
