# Generated by Django 4.1.7 on 2023-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_categoryreagents_name_ru_categoryreagents_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconsumables',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryconsumables',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='manufacturer_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='manufacturer_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='model_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='model_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='organization_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='organization_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
