# Generated by Django 4.1.7 on 2023-04-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_categoryservice_name_ru_categoryservice_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liders',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_images', to='polls.equipment'),
        ),
    ]
