# Generated by Django 4.1.7 on 2023-04-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_liders_views_alter_equipmentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liders',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='polls.liderscategories'),
        ),
    ]
