# Generated by Django 4.1.7 on 2023-04-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_liders_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentimage',
            old_name='Image',
            new_name='equipment',
        ),
    ]
