# Generated by Django 4.1.7 on 2023-04-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_repairimage_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='liders',
            name='touch',
            field=models.IntegerField(default=0),
        ),
    ]
