# Generated by Django 4.1.7 on 2023-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_liders_touch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'баннер', 'verbose_name_plural': 'баннер'},
        ),
        migrations.AlterModelOptions(
            name='categoryconsumables',
            options={'verbose_name': 'Категория Расходный материал', 'verbose_name_plural': 'Категория Расходный материал'},
        ),
        migrations.AlterModelOptions(
            name='categoryoborodvnya',
            options={'verbose_name': 'Категория Обородвинья', 'verbose_name_plural': 'Категория Обородвинья'},
        ),
        migrations.AlterModelOptions(
            name='categoryreagents',
            options={'verbose_name': 'Категория Реагенты', 'verbose_name_plural': 'Категория Реагенты'},
        ),
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'verbose_name': 'Категория Сервис', 'verbose_name_plural': 'Категория Сервис'},
        ),
        migrations.AlterModelOptions(
            name='consumables',
            options={'verbose_name': 'Расходный материал', 'verbose_name_plural': 'Расходный материал'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Обородвинья', 'verbose_name_plural': 'Обородвинья'},
        ),
        migrations.AlterModelOptions(
            name='liders',
            options={'verbose_name': 'рекламы', 'verbose_name_plural': 'рекламы'},
        ),
        migrations.AlterModelOptions(
            name='liderscategories',
            options={'verbose_name': 'Категория рекламы', 'verbose_name_plural': 'Категория рекламы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новости', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'партнёры', 'verbose_name_plural': 'партнёры'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Запчасти', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterModelOptions(
            name='reagents',
            options={'verbose_name': 'Реагенты', 'verbose_name_plural': 'Реагенты'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Ремонт', 'verbose_name_plural': 'Ремонт'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'входящие письма', 'verbose_name_plural': 'входящие письма'},
        ),
        migrations.AlterModelOptions(
            name='requestcall',
            options={'verbose_name': 'заказанные звонки', 'verbose_name_plural': 'заказанные звонки'},
        ),
        migrations.AlterModelOptions(
            name='web',
            options={'verbose_name': 'информация о сайте', 'verbose_name_plural': 'информация о сайте'},
        ),
    ]
